apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: alertmanager-main
  namespace: monitoring
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - alertmanager.localhost
  http:
  - match:
    - uri:
      - prefix: /
    route:
    - destination:
        host: alertmanager-main
        port: "9093"
