apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - grafana.localhost
  http:
  - match:
    - uri:
      - prefix: /
    route:
    - destination:
        host: grafana
        port: http
