apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - prometheus.localhost
  http:
  - match:
    - uri:
      - prefix: /
    route:
    - destination:
        host: prometheus-k8s
        port: "9090"
